export const locations = [
  {
    id: '1',
    name: 'Puerta del Sol',
    lat: 40.4169,
    lng: -3.7035,
    status: 'active',
    address: 'Plaza de la Puerta del Sol, s/n',
  },
  {
    id: '2',
    name: 'Parque del Retiro',
    lat: 40.4153,
    lng: -3.6844,
    status: 'inactive',
    address: 'Plaza de la Independencia, 7',
  },
  {
    id: '3',
    name: 'Plaza Mayor',
    lat: 40.4155,
    lng: -3.7074,
    status: 'active',
    address: 'Plaza Mayor, Madrid',
  },
  {
    id: '4',
    name: 'Museo del Prado',
    lat: 40.4137,
    lng: -3.6921,
    status: 'active',
    address: 'Calle de Ruiz de Alarcón, 23',
  },
  {
    id: '5',
    name: 'Puerta de Alcalá',
    lat: 40.4199,
    lng: -3.6887,
    status: 'active',
    address: 'Plaza de la Independencia, 1',
  },
  {
    id: '6',
    name: 'Estación de Atocha',
    lat: 40.4067,
    lng: -3.6904,
    status: 'active',
    address: 'Glorieta del Emperador Carlos V',
  },
  {
    id: '7',
    name: 'Templo de Debod',
    lat: 40.4241,
    lng: -3.7177,
    status: 'active',
    address: 'Calle de Ferraz, 1',
  },
  {
    id: '8',
    name: 'Palacio Real',
    lat: 40.4173,
    lng: -3.7143,
    status: 'active',
    address: 'Calle de Bailén, s/n',
  },
  {
    id: '9',
    name: 'Plaza de Cibeles',
    lat: 40.4193,
    lng: -3.6931,
    status: 'active',
    address: 'Plaza de Cibeles, Madrid',
  },
];
